name: ritmo
description: Tu ritmo diario perfecto - Seguimiento inteligente de hábitos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Gestión de estado
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  animations: ^2.0.11

  # Persistencia de datos
  sqflite: ^2.3.0
  path: ^1.8.0

  # Firebase - Backend y autenticación
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1

  # Notificaciones locales - versión estable y compatible
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # Gráficos y estadísticas
  fl_chart: ^0.69.0

  # Utilidades
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  app_settings: ^5.1.1

  # Monetización
  google_mobile_ads: ^5.1.0
  # purchases_flutter: ^6.30.2  # Temporarily disabled due to v1 embedding issues

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.0  # For database testing on desktop

flutter:
  uses-material-design: true

  # Internationalization
  generate: true