// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO3GH1LBn207l95jMAGYOQJKh61Lar8YU',
    appId: '1:714120150879:web:12bae8190ed0658bd280ea',
    messagingSenderId: '714120150879',
    projectId: 'habito-pro-app',
    authDomain: 'habito-pro-app.firebaseapp.com',
    storageBucket: 'habito-pro-app.firebasestorage.app',
    measurementId: 'G-XYN2CDRXRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8p6Nx3gC0pEypERLV44eESiMARaBv3yE',
    appId: '1:714120150879:android:23d827530fac370dd280ea',
    messagingSenderId: '714120150879',
    projectId: 'habito-pro-app',
    storageBucket: 'habito-pro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9bSM-07DUIikLL7FN5Nwbki0GgmwafCs',
    appId: '1:714120150879:ios:d0ce57af3f6ba619d280ea',
    messagingSenderId: '714120150879',
    projectId: 'habito-pro-app',
    storageBucket: 'habito-pro-app.firebasestorage.app',
    iosClientId: '714120150879-gibuubkiclr47r69lnsab22mtv96c7a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitoPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9bSM-07DUIikLL7FN5Nwbki0GgmwafCs',
    appId: '1:714120150879:ios:d0ce57af3f6ba619d280ea',
    messagingSenderId: '714120150879',
    projectId: 'habito-pro-app',
    storageBucket: 'habito-pro-app.firebasestorage.app',
    iosClientId: '714120150879-gibuubkiclr47r69lnsab22mtv96c7a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitoPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO3GH1LBn207l95jMAGYOQJKh61Lar8YU',
    appId: '1:714120150879:web:a70c45b509b0d74ad280ea',
    messagingSenderId: '714120150879',
    projectId: 'habito-pro-app',
    authDomain: 'habito-pro-app.firebaseapp.com',
    storageBucket: 'habito-pro-app.firebasestorage.app',
    measurementId: 'G-F2S2VX278Q',
  );

}